fixtures:
  symlinks:
    dockeragent: "#{source_dir}"
  repositories:
  forge_modules:
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "4.12.0"
    docker:
      repo: "garethr/docker"
      ref: "5.3.0"
